CREATE SEQUENCE  "NOT_ENTITAT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "NOT_ENTITAT_TIPUS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "NOT_ENTITAT" (
    "ID" NUMBER(19,0),
	"CREATEDDATE" TIMESTAMP (6),
	"LASTMODIFIEDDATE" TIMESTAMP (6),
	"ACTIVA" NUMBER(1,0),
	"AMB_ENTREGA_CIE" NUMBER(1,0),
	"AMB_ENTREGA_DEH" NUMBER(1,0),
	"API_KEY" VARCHAR2(64 CHAR),
	"CODI" VARCHAR2(64 CHAR),
	"COLOR_FONS" VARCHAR2(1024 CHAR),
	"COLOR_LLETRA" VARCHAR2(1024 CHAR),
	"DESCRIPCIO" VARCHAR2(1024 CHAR),
	"DIR3_CODI" VARCHAR2(9 CHAR),
	"DIR3_CODI_REG" VARCHAR2(9 CHAR),
	"LOGO_CAP" RAW(1024),
	"LOGO_PEU" RAW(1024),
	"NOM" VARCHAR2(256 CHAR),
	"TIPUS" VARCHAR2(32 CHAR),
	"TIPUS_DOC_DEFAULT" NUMBER(10,0),
    "OFICINA" VARCHAR2(255 CHAR),
    "NOM_OFICINA_VIRTUAL" VARCHAR2(255 CHAR),
    "LLIBRE" VARCHAR2(255 CHAR),
    "LLIBRE_NOM" VARCHAR2(255 CHAR),
    "LLIBRE_ENTITAT" NUMBER(1,0),
	"VERSION" NUMBER(19,0),
	"CREATEDBY_CODI" VARCHAR2(64 CHAR),
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR)
);

CREATE UNIQUE INDEX "NOT_ENTITAT_PK" ON "NOT_ENTITAT" ("ID");
CREATE UNIQUE INDEX "NOT_ENTITAT_UK" ON "NOT_ENTITAT" ("CODI");

ALTER TABLE "NOT_ENTITAT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOT_ENTITAT" MODIFY ("ACTIVA" NOT NULL ENABLE);
ALTER TABLE "NOT_ENTITAT" MODIFY ("AMB_ENTREGA_CIE" NOT NULL ENABLE);
ALTER TABLE "NOT_ENTITAT" MODIFY ("AMB_ENTREGA_DEH" NOT NULL ENABLE);
ALTER TABLE "NOT_ENTITAT" MODIFY ("API_KEY" NOT NULL ENABLE);
ALTER TABLE "NOT_ENTITAT" MODIFY ("CODI" NOT NULL ENABLE);
ALTER TABLE "NOT_ENTITAT" MODIFY ("DIR3_CODI" NOT NULL ENABLE);
ALTER TABLE "NOT_ENTITAT" MODIFY ("NOM" NOT NULL ENABLE);
ALTER TABLE "NOT_ENTITAT" MODIFY ("TIPUS" NOT NULL ENABLE);
ALTER TABLE "NOT_ENTITAT" MODIFY ("VERSION" NOT NULL ENABLE);
ALTER TABLE "NOT_ENTITAT" ADD PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "NOT_ENTITAT" ADD UNIQUE ("CODI") ENABLE;


--------------------------------------------------------
--  DDL for Table NOT_ENTITAT_TIPUS_DOC
--------------------------------------------------------

CREATE TABLE "NOT_ENTITAT_TIPUS_DOC" (
    "ID" NUMBER(19,0),
	"CREATEDDATE" TIMESTAMP (6),
	"LASTMODIFIEDDATE" TIMESTAMP (6),
	"TIPUS_DOC" NUMBER(10,0),
	"CREATEDBY_CODI" VARCHAR2(64 CHAR),
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR),
	"ENTITAT_ID" NUMBER(19,0)
);

CREATE UNIQUE INDEX "NOT_ENTITAT_TIPUS_DOC_PK" ON "NOT_ENTITAT_TIPUS_DOC" ("ID");

ALTER TABLE "NOT_ENTITAT_TIPUS_DOC" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOT_ENTITAT_TIPUS_DOC" ADD PRIMARY KEY ("ID") ENABLE;

ALTER TABLE "NOT_ENTITAT_TIPUS_DOC" ADD CONSTRAINT "NOT_ENTITAT_TIPUS_DOC_FK" FOREIGN KEY ("ENTITAT_ID") REFERENCES "NOT_ENTITAT" ("ID") ENABLE;


CREATE TABLE "NOT_ENTITAT_AUDIT"(
	"ID" NUMBER(19,0) NOT NULL,
	"TIPUSOPERACIO" VARCHAR2 (20 CHAR) NOT NULL,
   	"JOINPOINT" VARCHAR2 (256 CHAR),
	"CREATEDBY_CODI" VARCHAR2(64 CHAR),
	"CREATEDDATE" TIMESTAMP (6),
	"LASTMODIFIEDBY_CODI" VARCHAR2(64 CHAR),
	"LASTMODIFIEDDATE" TIMESTAMP (6),
	"ENTITAT_ID" NUMBER(19,0) NOT NULL,
	"CODI" VARCHAR2(64 CHAR) NOT NULL,
	"NOM" VARCHAR2(256 CHAR) NOT NULL,
	"TIPUS" VARCHAR2(32 CHAR),
	"DIR3_CODI" VARCHAR2(9 CHAR) NOT NULL,
	"DIR3_CODI_REG" VARCHAR2(9 CHAR),
	"API_KEY" VARCHAR2(64 CHAR),
	"AMB_ENTREGA_DEH" NUMBER(1,0),
	"AMB_ENTREGA_CIE" NUMBER(1,0),
	"DESCRIPCIO" VARCHAR2(1024 CHAR),
	"ACTIVA" NUMBER(1,0),
	"OFICINA" VARCHAR2(255 CHAR),
	"LLIBRE_ENTITAT" NUMBER(1,0),
	"LLIBRE" VARCHAR2(255 CHAR),
	"LLIBRE_NOM" VARCHAR2(255 CHAR)
);
ALTER TABLE NOT_ENTITAT_AUDIT ADD (CONSTRAINT NOT_ENTITAT_AUDIT_PK PRIMARY KEY (ID));
CREATE INDEX "NOT_ENTITAT_AUDIT_EK" ON "NOT_ENTITAT_AUDIT" ("ENTITAT_ID");
